# -*- coding: utf-8 -*-
"""CienciaEmRUSTassincrono.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m_h8W-TLbviNNPoHqgCSqbOvkCs58XLr
"""

# Sim, baixar RUST dentro do ipynb e usar RUST em vez de PYTHON para verificar as curiosidades que eu tenho sobre RUST

!curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

# Comando para que o ipynb reconheça os comandos CARGO e RUSTC
import os
os.environ['PATH'] += ":/root/.cargo/bin"

# Geralmente, em RUST, precisamos criar uma pasta de projetos. (quase igual o Java)
# nome deve ser tudo minusculo por preferencia do compilador
!cargo new projetocdadosrust

# Commented out IPython magic to ensure Python compatibility.
# Para rodar o projeto, o comando deve ser executado dentro do projeto. Não fora.
# %cd projetocdadosrust/

import kagglehub
import shutil
import os

# 1. Download do Kaggle
path = kagglehub.dataset_download("algozee/cyber-security")

# 2. Mapear arquivos para a pasta src do Rust
arquivos = ["financial_impact (1).csv", "incidents_master.csv", "market_impact.csv"]
src_path = "/content/projetocdadosrust/src"

for f in arquivos:
    origem = os.path.join(path, f)
    destino = os.path.join(src_path, f)
    if os.path.exists(origem):
        shutil.copy(origem, destino)
        print(f"✅ {f} movido para src/")

print("\n📂 Arquivos prontos para o processamento em Rust!")

!pip install seaborn

# Comando para rodar o projeto e ver que funciona kk
!cargo run

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/main.rs
# 
# fn main() {
#     println!("Rodando via Cargo no Colab!");
# }

# :D // nao tem muito o que dizer nessa sessão.
!cargo run

# criando uma pasta para adicionar codigos executaveis separaveis
!mkdir -p src/bin

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/bin/analise_extra.rs
# fn main() {
#     println!("Executando um arquivo secundário!");
#     println!("Isso é o equivalente a rodar um 'python analise_extra.py'");
# }

# agora ele chama especificamente o codigo separado em vez do main principal que vai ser usado para analise de dados.
!cargo run --bin analise_extra

"""a partir daqui irei explicar com menos frequencia."""

# adicionando uma biblioteca. Ele vai direto no cargo.toml, semelhante a pom.xml do Java quando se cria um projeto Maven
!cargo add csv

# biblioteca com a função de utilizar a placa de video. (Deixar a tarefa assincrona, fazer ao mesmo tempo)
# só essa parte é única e diferente de outros projetos python kkk
!cargo add tokio --features full

"""biblioteca para botar tempo de modificação na camada bronze

"""

!cargo add chrono@0.4.41 uuid

# pandas do RUST basicamente.
!cargo add polars --features lazy,parquet

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/bin/processamento_paralelo.rs
# use polars::prelude::*;
# use std::error::Error;
# use std::fs::{self, File};
# use std::time::Instant;
# use tokio::task;
# use chrono::Utc;
# use uuid::Uuid;
# 
# // Função assíncrona que faz o pipeline: CSV Bruto -> Adição de Metadados -> Parquet Bronze
# async fn ingerir_csv_para_bronze(nome_arquivo: String) -> Result<(), Box<dyn Error + Send + Sync>> {
#     // No Jupyter, assumimos que os arquivos .csv estão na pasta raiz do colab/projeto
#     let caminho_origem = format!("src/{}.csv", nome_arquivo);
#     let caminho_destino = format!("camada_bronze/{}.parquet", nome_arquivo);
# 
#     println!("🔄 Iniciando: Lendo de '{}' -> Convertendo para '{}'", caminho_origem, caminho_destino);
# 
#     task::spawn_blocking(move || -> Result<(), Box<dyn Error + Send + Sync>> {
# 
#         // 1. EXTRAÇÃO
#         let df = LazyCsvReader::new(caminho_origem.as_str().into())
#             .with_has_header(true)
#             .with_infer_schema_length(Some(10000))
#             .finish()?
#             .collect()?;
# 
#         let linhas = df.height() as u32;
# 
#         // 2. GERAÇÃO DOS METADADOS DE INGESTÃO (Requisito da Faculdade)
#         let timestamp_carga = Utc::now().to_rfc3339(); // Formato de data ISO 8601
#         let hash_lote = Uuid::new_v4().to_string();   // Hash único (ID do lote de carga)
# 
#         // Adiciona as 4 colunas de auditoria em todas as linhas da tabela
#         let mut df_bronze = df.lazy().with_columns([
#             lit(nome_arquivo.clone()).alias("meta_arquivo_origem"),
#             lit(linhas).alias("meta_qtd_linhas"),
#             lit(hash_lote).alias("meta_hash_ingestao"),
#             lit(timestamp_carga).alias("meta_data_carga"),
#         ]).collect()?;
# 
#         // 3. CARREGAMENTO (LOAD)
#         let mut arquivo_destino = File::create(&caminho_destino)?;
#         ParquetWriter::new(&mut arquivo_destino).finish(&mut df_bronze)?;
# 
#         println!("✅ Concluído: '{}' salvo com {} linhas processadas!", caminho_destino, linhas);
# 
#         Ok(())
#     }).await??;
# 
#     Ok(())
# }
# 
# #[tokio::main]
# async fn main() -> Result<(), Box<dyn Error>> {
#     let inicio = Instant::now();
# 
#     let pasta_bronze = "camada_bronze";
#     fs::create_dir_all(pasta_bronze)?;
#     println!("📁 Diretório '{}' criado/verificado!\n", pasta_bronze);
# 
#     let arquivos = vec![
#         "incidents_master".to_string(),
#         "market_impact".to_string(),
#         "financial_impact (1)".to_string(),
#     ];
# 
#     println!("🚀 Disparando tarefas paralelas com Tokio...\n");
# 
#     let mut handles = vec![];
# 
#     for arquivo in arquivos {
#         let handle = tokio::spawn(async move {
#             if let Err(e) = ingerir_csv_para_bronze(arquivo.clone()).await {
#                 eprintln!("❌ Erro catastrófico no arquivo {}: {}", arquivo, e);
#             }
#         });
#         handles.push(handle);
#     }
# 
#     for handle in handles {
#         handle.await?;
#     }
# 
#     println!("\n🏁 Pipeline de Ingestão Camada Bronze Finalizado!");
#     println!("⏱️ Tempo total gasto: {:?}", inicio.elapsed());
# 
#     Ok(())
# }

!cargo run --bin processamento_paralelo

"""tem uma media de tempo gasto para gerar que é torno de 360ms
e um tempo para compilar o projeto que é 7 minutos (eu diria que é culpa do colab kk)

e a estabilização demora 27 minutos no google colab
"""

# este comando vai tornar a velocidade de processamento dos csv mais rapido
!cargo run --release --bin processamento_paralelo

!cargo run --bin processamento_paralelo

# Preparação das tabelas antileakage

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/bin/extrair_schema.rs
# use polars::prelude::*;
# use std::error::Error;
# 
# fn main() -> Result<(), Box<dyn Error>> {
#     let arquivos = vec![
#         "camada_bronze/incidents_master.parquet",
#         "camada_bronze/market_impact.parquet",
#         "camada_bronze/financial_impact (1).parquet",
#     ];
# 
#     for arquivo in arquivos {
#         let nome_tabela = arquivo.split('/').last().unwrap_or(arquivo).replace(".parquet", "");
#         println!("### Tabela: {}", nome_tabela);
# 
#         // CORREÇÃO: Adicionando 'mut' como o compilador exigiu
#         let mut lf = LazyFrame::scan_parquet(arquivo.into(), ScanArgsParquet::default())?;
# 
#         let schema = lf.collect_schema()?;
#         let colunas: Vec<String> = schema.iter_names().map(|n| n.to_string()).collect();
# 
#         println!("{}", colunas.join(", "));
#         println!("{:-<50}", "");
#     }
# 
#     Ok(())
# }

# Commented out IPython magic to ensure Python compatibility.
# O %cd muda a pasta permanentemente para as próximas células
# %cd /home/the0hax/Área de trabalho/sabor/projetocdadosrust

!cargo run --bin extrair_schema

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/bin/data_quality.rs
# use polars::prelude::*;
# use std::error::Error;
# 
# fn main() -> Result<(), Box<dyn Error>> {
#     let arquivos = vec![
#         "camada_bronze/incidents_master.parquet",
#         "camada_bronze/market_impact.parquet",
#         "camada_bronze/financial_impact (1).parquet",
#     ];
# 
#     println!("📊 RELATÓRIO DE QUALIDADE DE DADOS (CAMADA BRONZE)\n{}", "=".repeat(60));
# 
#     for arquivo in arquivos {
#         let nome_tabela = arquivo.split('/').last().unwrap_or(arquivo).replace(".parquet", "");
# 
#         let lf = LazyFrame::scan_parquet(arquivo.into(), ScanArgsParquet::default())?;
#         let df = lf.clone().collect()?;
#         let total_linhas = df.height();
# 
#         let df_unique = lf.clone().unique(None, UniqueKeepStrategy::First).collect()?;
#         let duplicadas = total_linhas - df_unique.height();
# 
#         println!("\n📁 Tabela: {}", nome_tabela.to_uppercase());
#         println!("Total de Registros: {}", total_linhas);
# 
#         let pct_dup = if total_linhas > 0 { (duplicadas as f64 / total_linhas as f64) * 100.0 } else { 0.0 };
#         println!("Linhas Duplicadas: {} ({:.2}%)", duplicadas, pct_dup);
# 
#         println!("\n⚠️ Colunas com Valores Nulos:");
#         let mut tem_nulos = false;
# 
#         // CORREÇÃO: Estratégia moderna de iteração (Zero-Copy)
#         for nome_coluna in df.get_column_names() {
#             // Acessa a coluna (Series) de forma segura através do nome
#             let col = df.column(nome_coluna)?;
#             let qtd_nulos = col.null_count();
# 
#             if qtd_nulos > 0 {
#                 tem_nulos = true;
#                 let pct_nulos = (qtd_nulos as f64 / total_linhas as f64) * 100.0;
#                 println!("   - {}: {} nulos ({:.2}%)", col.name(), qtd_nulos, pct_nulos);
#             }
#         }
# 
#         if !tem_nulos {
#             println!("✅ Nenhuma coluna possui valores nulos.");
#         }
#         println!("{}", "-".repeat(60));
#     }
# 
#     Ok(())
# }

!cargo run --bin data_quality

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/bin/camada_prata.rs
# use polars::prelude::*;
# use std::error::Error;
# use std::fs::{self, File};
# 
# fn main() -> Result<(), Box<dyn Error>> {
#     println!("🚀 Iniciando o processamento da Camada Prata...");
# 
#     // 1. Isolar a variável alvo (Label) da tabela financeira
#     let lf_financeiro = LazyFrame::scan_parquet("camada_bronze/financial_impact (1).parquet".into(), ScanArgsParquet::default())?
#         .select([col("incident_id"), col("total_loss_usd")]);
# 
#     // 2. Carregar a tabela principal de incidentes
#     let lf_incidentes = LazyFrame::scan_parquet("camada_bronze/incidents_master.parquet".into(), ScanArgsParquet::default())?;
# 
#     // 3. Cruzamento de Dados (Inner Join)
#     let mut lf_prata = lf_incidentes
#         .inner_join(lf_financeiro, col("incident_id"), col("incident_id"));
# 
#     // 4. ESTRATÉGIA DINÂMICA ANTI-LEAKAGE (À Prova de Erros de Versão)
#     let schema = lf_prata.collect_schema()?;
# 
#     let colunas_para_dropar = vec![
#         "downtime_hours", "data_compromised_records", "disclosure_date",
#         "company_name", "stock_ticker", "notes", "created_at", "updated_at",
#         "industry_secondary", "attack_vector_secondary", "review_flag",
#         "meta_arquivo_origem", "meta_qtd_linhas", "meta_hash_ingestao", "meta_data_carga",
#         "incident_id"
#     ];
# 
#     // CORREÇÃO APLICADA: nome.as_str() garante a compatibilidade do tipo
#     let colunas_a_manter: Vec<Expr> = schema.iter_names()
#         .filter(|&nome| !colunas_para_dropar.contains(&nome.as_str()))
#         .map(|nome| col(nome.as_str()))
#         .collect();
# 
#     // 5. Aplicar o Select Limpo e Tratar os Nulos
#     lf_prata = lf_prata
#         .select(colunas_a_manter)
#         .filter(col("total_loss_usd").is_not_null())
#         .with_columns([
#             col("attack_chain").fill_null(lit("Desconhecido")),
#             col("attributed_group").fill_null(lit("Desconhecido")),
#             col("attribution_confidence").fill_null(lit("Desconhecido")),
#             col("data_type").fill_null(lit("Desconhecido")),
#             col("data_source_secondary").fill_null(lit("Desconhecido")),
#         ]);
# 
#     // 6. Coletar e processar a tabela na memória RAM
#     let mut df_prata = lf_prata.collect()?;
# 
#     println!("✅ Transformações concluídas! Dataset ML limpo gerado com: {} linhas x {} colunas", df_prata.height(), df_prata.width());
# 
#     // 7. Salvar o arquivo final na Camada Prata
#     fs::create_dir_all("camada_prata")?;
#     let caminho_destino = "camada_prata/dataset_ml_final.parquet";
#     let mut arquivo_destino = File::create(caminho_destino)?;
#     ParquetWriter::new(&mut arquivo_destino).finish(&mut df_prata)?;
# 
#     println!("💾 Dataset salvo com sucesso em: {}", caminho_destino);
# 
#     Ok(())
# }

!cargo run --bin camada_prata

# Fase 4, iremos permanecer no RUST e visualizar a capacidade que o RUST é capaz de produzir (Se o codigo ficar muito ruim, o python acabará ganhando kk)

!cargo add plotly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile src/bin/eda.rs
# use polars::prelude::*;
# use plotly::{Plot, Bar};
# use plotly::layout::{Layout, Axis};
# use plotly::common::{Title, Marker};
# use std::error::Error;
# 
# fn main() -> Result<(), Box<dyn Error>> {
#     println!("📊 Gerando visualizações de alto nível em Rust...");
# 
#     let df = LazyFrame::scan_parquet("camada_prata/dataset_ml_final.parquet".into(), ScanArgsParquet::default())?
#         .collect()?;
# 
#     // ====================================================================
#     // GRÁFICO 1: Indústrias Mais Atacadas (Cor: Vermelho Escuro)
#     // ====================================================================
#     let df_ind = df.clone().lazy()
#         .group_by([col("industry_primary")])
#         .agg([len().alias("count")])
#         .sort(["count"], SortMultipleOptions::default().with_order_descending(true))
#         .limit(10)
#         .collect()?;
# 
#     let x_ind: Vec<String> = df_ind.column("industry_primary")?.cast(&DataType::String)?.str()?.into_iter().map(|s| s.unwrap_or("N/A").to_string()).collect();
#     let y_ind: Vec<f64> = df_ind.column("count")?.cast(&DataType::Float64)?.f64()?.into_iter().map(|v| v.unwrap_or(0.0)).collect();
# 
#     let trace1 = Bar::new(x_ind, y_ind)
#         .name("Incidentes")
#         .marker(Marker::new().color("#8B0000"));
# 
#     // CORREÇÃO: Utilizando Title::new().text("...")
#     let layout1 = Layout::new()
#         .title(Title::new().text("Top 10 Indústrias com Maior Volume de Ataques"))
#         .x_axis(Axis::new().title(Title::new().text("Setor da Indústria")))
#         .y_axis(Axis::new().title(Title::new().text("Quantidade de Ataques Registrados")));
# 
#     let mut plot1 = Plot::new();
#     plot1.add_trace(trace1);
#     plot1.set_layout(layout1);
#     plot1.write_html("eda_grafico1.html");
# 
#     // ====================================================================
#     // GRÁFICO 2: Prejuízo Médio por Vetor (Cor: Azul Aço)
#     // ====================================================================
#     let df_vec = df.clone().lazy()
#         .group_by([col("attack_vector_primary")])
#         .agg([col("total_loss_usd").mean().alias("avg_loss")])
#         .sort(["avg_loss"], SortMultipleOptions::default().with_order_descending(true))
#         .limit(10)
#         .collect()?;
# 
#     let x_vec: Vec<String> = df_vec.column("attack_vector_primary")?.cast(&DataType::String)?.str()?.into_iter().map(|s| s.unwrap_or("N/A").to_string()).collect();
#     let y_vec: Vec<f64> = df_vec.column("avg_loss")?.cast(&DataType::Float64)?.f64()?.into_iter().map(|v| v.unwrap_or(0.0)).collect();
# 
#     let trace2 = Bar::new(x_vec, y_vec)
#         .name("Prejuízo Médio")
#         .marker(Marker::new().color("#4682B4"));
# 
#     // CORREÇÃO APLICADA
#     let layout2 = Layout::new()
#         .title(Title::new().text("Impacto Financeiro: Prejuízo Médio por Vetor de Ataque"))
#         .x_axis(Axis::new().title(Title::new().text("Vetor de Invasão (Origem)")))
#         .y_axis(Axis::new().title(Title::new().text("Prejuízo Médio Estimado (USD)")));
# 
#     let mut plot2 = Plot::new();
#     plot2.add_trace(trace2);
#     plot2.set_layout(layout2);
#     plot2.write_html("eda_grafico2.html");
# 
#     // ====================================================================
#     // GRÁFICO 3: Tipos de Dados Vazados (Cor: Verde Esmeralda)
#     // ====================================================================
#     let df_data = df.clone().lazy()
#         .group_by([col("data_type")])
#         .agg([len().alias("count")])
#         .sort(["count"], SortMultipleOptions::default().with_order_descending(true))
#         .limit(10)
#         .collect()?;
# 
#     let x_data: Vec<String> = df_data.column("data_type")?.cast(&DataType::String)?.str()?.into_iter().map(|s| s.unwrap_or("N/A").to_string()).collect();
#     let y_data: Vec<f64> = df_data.column("count")?.cast(&DataType::Float64)?.f64()?.into_iter().map(|v| v.unwrap_or(0.0)).collect();
# 
#     let trace3 = Bar::new(x_data, y_data)
#         .name("Vazamentos")
#         .marker(Marker::new().color("#50C878"));
# 
#     // CORREÇÃO APLICADA
#     let layout3 = Layout::new()
#         .title(Title::new().text("Alvos Preferenciais: Frequência de Tipos de Dados Roubados"))
#         .x_axis(Axis::new().title(Title::new().text("Classificação do Dado")))
#         .y_axis(Axis::new().title(Title::new().text("Número de Ocorrências")));
# 
#     let mut plot3 = Plot::new();
#     plot3.add_trace(trace3);
#     plot3.set_layout(layout3);
#     plot3.write_html("eda_grafico3.html");
# 
#     println!("✅ Gráficos profissionais gerados com sucesso!");
#     Ok(())
# }

!cargo run --bin eda

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("📊 Fase 4: Análise Exploratória de Dados (Renderização Nativa)")
print("Lendo o dataset limpo da Camada Prata gerado pelo Rust...")

# 1. Carrega o dataset limpo que o nosso Rust preparou
df = pd.read_parquet("/content/projetocdadosrust/camada_prata/dataset_ml_final.parquet")

# Configuração visual global
sns.set_theme(style="whitegrid")
fig, axes = plt.subplots(3, 1, figsize=(12, 18))

# ====================================================================
# GRÁFICO 1: Indústrias Mais Atacadas
# ====================================================================
sns.countplot(
    data=df,
    y="industry_primary",
    order=df['industry_primary'].value_counts().iloc[:10].index,
    hue="industry_primary", # Adequação à nova API do Seaborn
    legend=False,           # Evita legenda redundante
    palette="Reds_r",
    ax=axes[0]
)
axes[0].set_title("Top 10 Indústrias com Maior Volume de Ataques", fontsize=14, fontweight='bold')
axes[0].set_xlabel("Quantidade de Ataques Registrados")
axes[0].set_ylabel("Setor da Indústria")

# ====================================================================
# GRÁFICO 2: Prejuízo Médio por Vetor
# ====================================================================
avg_loss = df.groupby("attack_vector_primary")["total_loss_usd"].mean().sort_values(ascending=False).head(10)
sns.barplot(
    x=avg_loss.values,
    y=avg_loss.index,
    hue=avg_loss.index,     # Adequação à nova API do Seaborn
    legend=False,
    palette="Blues_r",
    ax=axes[1]
)
axes[1].set_title("Impacto Financeiro: Prejuízo Médio por Vetor de Ataque (USD)", fontsize=14, fontweight='bold')
axes[1].set_xlabel("Prejuízo Médio Estimado (USD)")
axes[1].set_ylabel("Vetor de Invasão (Origem)")

# ====================================================================
# GRÁFICO 3: Tipos de Dados Vazados
# ====================================================================
sns.countplot(
    data=df,
    y="data_type",
    order=df['data_type'].value_counts().iloc[:10].index,
    hue="data_type",        # Adequação à nova API do Seaborn
    legend=False,
    palette="Greens_r",
    ax=axes[2]
)
axes[2].set_title("Alvos Preferenciais: Frequência de Tipos de Dados Roubados", fontsize=14, fontweight='bold')
axes[2].set_xlabel("Número de Ocorrências")
axes[2].set_ylabel("Classificação do Dado")

# Ajuste de layout para evitar sobreposição
plt.tight_layout()
plt.show()